package controlador;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class CapturaPokemonController {
	@FXML
	private Button btnCapturar;
	@FXML
	private Button btnBuscar;
	@FXML
	private Label lblPokemonCapturar;

	// Event Listener on Button[#btnCapturar].onAction
	@FXML
	public void capturar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBuscar].onAction
	@FXML
	public void buscar(ActionEvent event) {
		// TODO Autogenerated
	}
}
